### ISSUE TITLE
Seems to be functioning just fine on desktop ubuntu?

### ISSUE THREAD

**Issue by alexwhittemore** [adafruit/Adafruit_CircuitPython_RPLIDAR#10]
The package description on PyPi for adafruit_rplidar (at https://pypi.org/project/adafruit-rplidar/) states

> Eventual goal is for the single module to work with both Linux (via /dev/USB0, etc) and CircuitPython (via a UART instance)

Is there any reason to suspect this goal isn't yet achieved? I'm prototyping a project for eventual raspberry pi deployment in a Ubuntu 18.04 VM, and this seems to work just fine - haven't run into any compatibility problems yet. 

As usual, thanks for being awesome!

**Comment by ladyada** [comment]
should 'just work' -  thats probably just an old notice
@dherrada

**Comment by dherrada** [comment]
@ladyada looks like releases haven't been going to pypi. I'll look into it

**Comment by alexwhittemore** [comment]
only on github.com/adafruit do you post an issue about the lack of issues when documentation suggests there might be an issue, only to find out the actual issue is that you're running on an out-of-date version and missing things you didn't know you were missing.

**Comment by dherrada** [comment]
@dastels Can you remove [this pypi project](https://pypi.org/project/adafruit-rplidar/)? It seems to be under your name.

**Comment by dherrada** [comment]
@ladyada So it looks like what happened was that the very first release of this library got put on another pypi project which hasn't been updated since.

**Comment by dherrada** [comment]
@alexwhittemore here's the right library: https://pypi.org/project/adafruit-circuitpython-rplidar/

**Comment by alexwhittemore** [comment]
Ahh - I HAD noticed the discrepancy in library name, and I think I just assumed there were two separate versions for the different venues, rather than realizing the name just changed at some point. So I suppose the real root issue is that this Learn article references the outdated name, which is still functional because the old-name pypi project exists: https://learn.adafruit.com/slamtec-rplidar-on-pi/cpython-on-raspberry-pi

Anyway I'll try the correct references, but I have to assume it'll still work :)

**Comment by dherrada** [comment]
@alexwhittemore Thanks for linking to that. I'll correct that right away.

**Comment by alexwhittemore** [comment]
Naturally the update works as a drop-in replacement. Although the original version didn't depend on circuitpython components that the current one does, so there's that.

Thanks!

**Comment by dherrada** [comment]
Closing. I believe this is resolved.
