### ISSUE TITLE
Problem resizing window

### ISSUE THREAD

**Issue by pyobox** [adafruit/Adafruit_CircuitPython_RPLIDAR#12]
Howdy  I've been using this code to run my slamtec rplidar, works well except I'm trying to run it with small display.  Therefor, I'm trying to resize the window however, the image doesn't change size, just the window. Please help.

**Comment by ladyada** [comment]
check these lines and pygame tutorials to adjust the display size you want

```
import os
from math import cos, sin, pi, floor
import pygame
from adafruit_circuitpython_rplidar import RPLidar

# Set up pygame and the display
os.putenv('SDL_FBDEV', '/dev/fb1')
pygame.init()
lcd = pygame.display.set_mode((320,240))
```
