### ISSUE TITLE
Still not sure how to fix the "Descriptor length mismatch" A1M8-R6 firmware issue

### ISSUE THREAD

**Issue by javadan** [adafruit/Adafruit_CircuitPython_RPLIDAR#25]
I see other users are asking this still, and their questions are just being closed.

But it would be nice to use the RPLidar (A1M8-R6)

The results of running the example (all required python libs installed)

> pi@raspberrypi:~/Adafruit_CircuitPython_RPLIDAR/examples $ python3 rplidar_simpletest.py
> Traceback (most recent call last):
>   File "/home/pi/Adafruit_CircuitPython_RPLIDAR/examples/rplidar_simpletest.py", line 24, in <module>
>     for scan in lidar.iter_scans():
>   File "/home/pi/.local/lib/python3.9/site-packages/adafruit_rplidar.py", line 540, in iter_scans
>     for new_scan, quality, angle, distance in iterator:
>   File "/home/pi/.local/lib/python3.9/site-packages/adafruit_rplidar.py", line 445, in iter_measurements
>     self.start(scan_type)
>   File "/home/pi/.local/lib/python3.9/site-packages/adafruit_rplidar.py", line 360, in start
>     status, error_code = self.health
>   File "/home/pi/.local/lib/python3.9/site-packages/adafruit_rplidar.py", line 328, in health
>     dsize, is_single, dtype = self._read_descriptor()
>   File "/home/pi/.local/lib/python3.9/site-packages/adafruit_rplidar.py", line 268, in _read_descriptor
>     raise RPLidarException("Descriptor length mismatch")
> adafruit_rplidar.RPLidarException: Descriptor length mismatch
> 

Any ideas?  Thanks

**Comment by makermelissa** [comment]
What firmware revision do you have? It was updated to work with version 1.29 in https://github.com/adafruit/Adafruit_CircuitPython_RPLIDAR/pull/17. It's possible your unit has something newer that added new features or broke compatibility.

**Comment by javadan** [comment]
Hi Melissa, I bought it on [digikey](https://www.digikey.co.za/en/products/detail/dfrobot/DFR0315/7597150), and it's branded as a DF Robot product.

The only info I can find in the specification is:
• Model: RPLIDAR A1M8-R6

Not sure how to verify firmware revision unfortunately.

**Comment by makermelissa** [comment]
The one I have is from Adafruit and is stuck on firmware 1.27. I think I was able to check that using the SLAMTEC software. You might want to see if that software works with yours. Without more information, this can be difficult to troubleshoot.

Some other possibilities I can think of might be it needing to be updated for the Python version (though unlikely) or your environment setup.

**Comment by javadan** [comment]
Ok thanks, I'll give the SLAMTEC software a go, next time I try.  Will probably leave it for a day or two.

**Comment by javadan** [comment]
Well, indeed it is 1.29.  The Firmware program refuses to upgrade/downgrade to 1.27.

From what I can see on various forums, it might be an issue of USB not providing enough power.  But I've tried with a USB3 port, so it's probably not that.

Hmm.  Dunno.  Anyway I'll close the issue.  Probably a power issue.  

`
C:\Users\db\Downloads>simple_grabber.exe \\.\COM9                                                                RPLIDAR S/N: XXXXXXXXXXXXXXXXXXXX(edited)                                                                           Version: 1.10.0                                                                                                         Firmware Ver: 1.29                                                                                                      Hardware Rev: 7                                                                                                         RPLidar health status : OK. (errorcode: 0)                                                                              waiting for data...                                                                                                     *WARN* YOU ARE USING DEPRECATED API: grabScanData(), PLEASE MOVE TO grabScanDataHq()                                    *WARN* YOU ARE USING DEPRECATED API: ascendScanData(rplidar_response_measurement_node_t*, size_t), PLEASE MOVE TO ascendScanData(rplidar_response_measurement_node_hq_t*, size_t)                                                               ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ***************************************************************************                                             ---------------------------------------------------------------------------                                             Do you want to see all the data? (y/n) y                                                                                Error, cannot grab scan data.    `

**Comment by javadan** [comment]
Followup:  I connected the motor to a dedicated 5V instead of the USB.  Still, same error message.  Damn.  $99 spinning plastic.

**Comment by javadan** [comment]
Followup: I ran frame_grabber.exe and it works! Ha.  Ok, now to try work out how to compile VS 2010 code missing various libraries, in 2022.

**Comment by makermelissa** [comment]
Thanks for finding this. Would you like to submit a PR with the fix? I could at least test and verify it runs on the older 1.27 firmware (which unfortunately doesn't appear to be upgradeable).

**Comment by javadan** [comment]
I also get a crash later, randomly, so I'll need to look at that too.  Seems fine to just catch and drop the exception though.

But if/when I get the visualisation working over a network, I'll submit a PR with a proper fix. ( The quick fix above is pretty hacky, and might swallow legitimate exceptions.  )


```   
File "/home/pi/.local/lib/python3.9/site-packages/adafruit_rplidar.py", line 99, in _process_scan
    raise RPLidarException("New scan flags mismatch")
```

**Comment by makermelissa** [comment]
I might see if getting a more recent RPLIDAR would have the latest firmware now
