### ISSUE TITLE
Change motor speed with A1 model

### ISSUE THREAD

**Issue by yanickrochon** [adafruit/Adafruit_CircuitPython_RPLIDAR#3]
According to Slamtec's [website](http://www.slamtec.com/en/lidar/a1), the motor can operate on variable speeds, however I have seen nowhere where this speed can be changed.

![image](https://user-images.githubusercontent.com/78461/68416834-3a510600-0163-11ea-8c28-b0284d842dc2.png)

Is this false advertisement, or is there something missing? Furthermore, the motor never stops spinning, even when the `.stop()` and `.disconnect()` methods are called.

**Comment by ladyada** [comment]
its been a while since we tried this code, maybe there's a typo in our implementation, it seems like you should be able to change the PWM rate
https://github.com/adafruit/Adafruit_CircuitPython_RPLIDAR/blob/master/adafruit_rplidar.py#L180

**Comment by yanickrochon** [comment]
Yes, we tried that. We even tried calling that method manually, but it does nothing.

**Comment by ladyada** [comment]
you could try looking at other python rplidar code or the code that is distributed by the manufacturer for hints

**Comment by yanickrochon** [comment]
We received an answer :

![image](https://user-images.githubusercontent.com/78461/68680696-2117d300-0530-11ea-94e2-c8792995a297.png)

**Comment by ladyada** [comment]
ok good to know!
