### ISSUE TITLE
Poor Reaction Time

### ISSUE THREAD

**Issue by jsl303** [adafruit/Adafruit_CircuitPython_RPLIDAR#9]
I have RPLIDAR A1M8, but reaction time is extremely poor.
It's kind of usable if an object gets closer. However, if the object gets further away, the reading increases very slowly.
Sometimes it even never recovers if the objects moves quickly.
I'm not sure if I received a defective unit, or it's a library problem.
Has anyone experienced this?

**Comment by ladyada** [comment]
@jsl303 hi what exact model did you purchase, plz paste a url :)

**Comment by jsl303** [comment]
https://www.adafruit.com/product/4010

**Comment by ladyada** [comment]
yeah we just read the raw data from that sensor - any computation is done within the electronics. they're low cost LIDARs so you wont get great resolution and reaction time

**Comment by dherrada** [comment]
Appears resolved. Closing
